"""Hand-curated country reference data.

Sourced from ISO 3166-1 (alpha2 / alpha3 / numeric), UN M49 (region /
subregion), ISO 4217 (currency codes), E.164 (calling codes), IANA
(ccTLDs), and the UN member list. Each entry is the authoritative copy
for this repository — edit in place to extend.

This file covers the ~80 most-queried countries, weighted towards G20 +
Europe + probe-relevant micro-states. Extending to all 249 ISO 3166-1
entries is a data-only change: add a dict to ``COUNTRIES`` and the
extractor will pick it up automatically.
"""

from __future__ import annotations


COUNTRIES: list[dict] = [
    # ---- G20 ----------------------------------------------------------
    {
        "name": "United States",
        "alpha2": "US", "alpha3": "USA", "numeric": "840",
        "capital": "Washington, D.C.",
        "continent": "North America", "region": "Americas", "subregion": "Northern America",
        "currency": "USD", "currency_name": "United States dollar",
        "calling_code": "+1", "tld": ".us",
        "languages": ["English"], "un_member": True,
    },
    {
        "name": "United Kingdom",
        "alpha2": "GB", "alpha3": "GBR", "numeric": "826",
        "capital": "London",
        "continent": "Europe", "region": "Europe", "subregion": "Northern Europe",
        "currency": "GBP", "currency_name": "Pound sterling",
        "calling_code": "+44", "tld": ".uk",
        "languages": ["English"], "un_member": True,
    },
    {
        "name": "China",
        "alpha2": "CN", "alpha3": "CHN", "numeric": "156",
        "capital": "Beijing",
        "continent": "Asia", "region": "Asia", "subregion": "Eastern Asia",
        "currency": "CNY", "currency_name": "Renminbi",
        "calling_code": "+86", "tld": ".cn",
        "languages": ["Mandarin"], "un_member": True,
    },
    {
        "name": "Japan",
        "alpha2": "JP", "alpha3": "JPN", "numeric": "392",
        "capital": "Tokyo",
        "continent": "Asia", "region": "Asia", "subregion": "Eastern Asia",
        "currency": "JPY", "currency_name": "Japanese yen",
        "calling_code": "+81", "tld": ".jp",
        "languages": ["Japanese"], "un_member": True,
    },
    {
        "name": "Germany",
        "alpha2": "DE", "alpha3": "DEU", "numeric": "276",
        "capital": "Berlin",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+49", "tld": ".de",
        "languages": ["German"], "un_member": True,
    },
    {
        "name": "France",
        "alpha2": "FR", "alpha3": "FRA", "numeric": "250",
        "capital": "Paris",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+33", "tld": ".fr",
        "languages": ["French"], "un_member": True,
    },
    {
        "name": "Italy",
        "alpha2": "IT", "alpha3": "ITA", "numeric": "380",
        "capital": "Rome",
        "continent": "Europe", "region": "Europe", "subregion": "Southern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+39", "tld": ".it",
        "languages": ["Italian"], "un_member": True,
    },
    {
        "name": "Canada",
        "alpha2": "CA", "alpha3": "CAN", "numeric": "124",
        "capital": "Ottawa",
        "continent": "North America", "region": "Americas", "subregion": "Northern America",
        "currency": "CAD", "currency_name": "Canadian dollar",
        "calling_code": "+1", "tld": ".ca",
        "languages": ["English", "French"], "un_member": True,
    },
    {
        "name": "Russia",
        "alpha2": "RU", "alpha3": "RUS", "numeric": "643",
        "capital": "Moscow",
        "continent": "Europe", "region": "Europe", "subregion": "Eastern Europe",
        "currency": "RUB", "currency_name": "Russian ruble",
        "calling_code": "+7", "tld": ".ru",
        "languages": ["Russian"], "un_member": True,
    },
    {
        "name": "Brazil",
        "alpha2": "BR", "alpha3": "BRA", "numeric": "076",
        "capital": "Brasília",
        "continent": "South America", "region": "Americas", "subregion": "South America",
        "currency": "BRL", "currency_name": "Brazilian real",
        "calling_code": "+55", "tld": ".br",
        "languages": ["Portuguese"], "un_member": True,
    },
    {
        "name": "India",
        "alpha2": "IN", "alpha3": "IND", "numeric": "356",
        "capital": "New Delhi",
        "continent": "Asia", "region": "Asia", "subregion": "Southern Asia",
        "currency": "INR", "currency_name": "Indian rupee",
        "calling_code": "+91", "tld": ".in",
        "languages": ["Hindi", "English"], "un_member": True,
    },
    {
        "name": "Mexico",
        "alpha2": "MX", "alpha3": "MEX", "numeric": "484",
        "capital": "Mexico City",
        "continent": "North America", "region": "Americas", "subregion": "Central America",
        "currency": "MXN", "currency_name": "Mexican peso",
        "calling_code": "+52", "tld": ".mx",
        "languages": ["Spanish"], "un_member": True,
    },
    {
        "name": "Australia",
        "alpha2": "AU", "alpha3": "AUS", "numeric": "036",
        "capital": "Canberra",
        "continent": "Oceania", "region": "Oceania", "subregion": "Australia and New Zealand",
        "currency": "AUD", "currency_name": "Australian dollar",
        "calling_code": "+61", "tld": ".au",
        "languages": ["English"], "un_member": True,
    },
    {
        "name": "South Korea",
        "alpha2": "KR", "alpha3": "KOR", "numeric": "410",
        "capital": "Seoul",
        "continent": "Asia", "region": "Asia", "subregion": "Eastern Asia",
        "currency": "KRW", "currency_name": "South Korean won",
        "calling_code": "+82", "tld": ".kr",
        "languages": ["Korean"], "un_member": True,
    },
    {
        "name": "Indonesia",
        "alpha2": "ID", "alpha3": "IDN", "numeric": "360",
        "capital": "Jakarta",
        "continent": "Asia", "region": "Asia", "subregion": "South-eastern Asia",
        "currency": "IDR", "currency_name": "Indonesian rupiah",
        "calling_code": "+62", "tld": ".id",
        "languages": ["Indonesian"], "un_member": True,
    },
    {
        "name": "Saudi Arabia",
        "alpha2": "SA", "alpha3": "SAU", "numeric": "682",
        "capital": "Riyadh",
        "continent": "Asia", "region": "Asia", "subregion": "Western Asia",
        "currency": "SAR", "currency_name": "Saudi riyal",
        "calling_code": "+966", "tld": ".sa",
        "languages": ["Arabic"], "un_member": True,
    },
    {
        "name": "Turkey",
        "alpha2": "TR", "alpha3": "TUR", "numeric": "792",
        "capital": "Ankara",
        "continent": "Asia", "region": "Asia", "subregion": "Western Asia",
        "currency": "TRY", "currency_name": "Turkish lira",
        "calling_code": "+90", "tld": ".tr",
        "languages": ["Turkish"], "un_member": True,
    },
    {
        "name": "South Africa",
        "alpha2": "ZA", "alpha3": "ZAF", "numeric": "710",
        "capital": "Pretoria",
        "continent": "Africa", "region": "Africa", "subregion": "Southern Africa",
        "currency": "ZAR", "currency_name": "South African rand",
        "calling_code": "+27", "tld": ".za",
        "languages": ["English", "Afrikaans", "Zulu", "Xhosa"], "un_member": True,
    },
    {
        "name": "Argentina",
        "alpha2": "AR", "alpha3": "ARG", "numeric": "032",
        "capital": "Buenos Aires",
        "continent": "South America", "region": "Americas", "subregion": "South America",
        "currency": "ARS", "currency_name": "Argentine peso",
        "calling_code": "+54", "tld": ".ar",
        "languages": ["Spanish"], "un_member": True,
    },
    # ---- Europe (rest) ------------------------------------------------
    {
        "name": "Spain",
        "alpha2": "ES", "alpha3": "ESP", "numeric": "724",
        "capital": "Madrid",
        "continent": "Europe", "region": "Europe", "subregion": "Southern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+34", "tld": ".es",
        "languages": ["Spanish"], "un_member": True,
    },
    {
        "name": "Netherlands",
        "alpha2": "NL", "alpha3": "NLD", "numeric": "528",
        "capital": "Amsterdam",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+31", "tld": ".nl",
        "languages": ["Dutch"], "un_member": True,
    },
    {
        "name": "Belgium",
        "alpha2": "BE", "alpha3": "BEL", "numeric": "056",
        "capital": "Brussels",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+32", "tld": ".be",
        "languages": ["Dutch", "French", "German"], "un_member": True,
    },
    {
        "name": "Switzerland",
        "alpha2": "CH", "alpha3": "CHE", "numeric": "756",
        "capital": "Bern",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "CHF", "currency_name": "Swiss franc",
        "calling_code": "+41", "tld": ".ch",
        "languages": ["German", "French", "Italian", "Romansh"], "un_member": True,
    },
    {
        "name": "Sweden",
        "alpha2": "SE", "alpha3": "SWE", "numeric": "752",
        "capital": "Stockholm",
        "continent": "Europe", "region": "Europe", "subregion": "Northern Europe",
        "currency": "SEK", "currency_name": "Swedish krona",
        "calling_code": "+46", "tld": ".se",
        "languages": ["Swedish"], "un_member": True,
    },
    {
        "name": "Norway",
        "alpha2": "NO", "alpha3": "NOR", "numeric": "578",
        "capital": "Oslo",
        "continent": "Europe", "region": "Europe", "subregion": "Northern Europe",
        "currency": "NOK", "currency_name": "Norwegian krone",
        "calling_code": "+47", "tld": ".no",
        "languages": ["Norwegian"], "un_member": True,
    },
    {
        "name": "Finland",
        "alpha2": "FI", "alpha3": "FIN", "numeric": "246",
        "capital": "Helsinki",
        "continent": "Europe", "region": "Europe", "subregion": "Northern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+358", "tld": ".fi",
        "languages": ["Finnish", "Swedish"], "un_member": True,
    },
    {
        "name": "Denmark",
        "alpha2": "DK", "alpha3": "DNK", "numeric": "208",
        "capital": "Copenhagen",
        "continent": "Europe", "region": "Europe", "subregion": "Northern Europe",
        "currency": "DKK", "currency_name": "Danish krone",
        "calling_code": "+45", "tld": ".dk",
        "languages": ["Danish"], "un_member": True,
    },
    {
        "name": "Iceland",
        "alpha2": "IS", "alpha3": "ISL", "numeric": "352",
        "capital": "Reykjavík",
        "continent": "Europe", "region": "Europe", "subregion": "Northern Europe",
        "currency": "ISK", "currency_name": "Icelandic króna",
        "calling_code": "+354", "tld": ".is",
        "languages": ["Icelandic"], "un_member": True,
    },
    {
        "name": "Ireland",
        "alpha2": "IE", "alpha3": "IRL", "numeric": "372",
        "capital": "Dublin",
        "continent": "Europe", "region": "Europe", "subregion": "Northern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+353", "tld": ".ie",
        "languages": ["English", "Irish"], "un_member": True,
    },
    {
        "name": "Poland",
        "alpha2": "PL", "alpha3": "POL", "numeric": "616",
        "capital": "Warsaw",
        "continent": "Europe", "region": "Europe", "subregion": "Eastern Europe",
        "currency": "PLN", "currency_name": "Polish złoty",
        "calling_code": "+48", "tld": ".pl",
        "languages": ["Polish"], "un_member": True,
    },
    {
        "name": "Austria",
        "alpha2": "AT", "alpha3": "AUT", "numeric": "040",
        "capital": "Vienna",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+43", "tld": ".at",
        "languages": ["German"], "un_member": True,
    },
    {
        "name": "Portugal",
        "alpha2": "PT", "alpha3": "PRT", "numeric": "620",
        "capital": "Lisbon",
        "continent": "Europe", "region": "Europe", "subregion": "Southern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+351", "tld": ".pt",
        "languages": ["Portuguese"], "un_member": True,
    },
    {
        "name": "Greece",
        "alpha2": "GR", "alpha3": "GRC", "numeric": "300",
        "capital": "Athens",
        "continent": "Europe", "region": "Europe", "subregion": "Southern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+30", "tld": ".gr",
        "languages": ["Greek"], "un_member": True,
    },
    {
        "name": "Czechia",
        "alpha2": "CZ", "alpha3": "CZE", "numeric": "203",
        "capital": "Prague",
        "continent": "Europe", "region": "Europe", "subregion": "Eastern Europe",
        "currency": "CZK", "currency_name": "Czech koruna",
        "calling_code": "+420", "tld": ".cz",
        "languages": ["Czech"], "un_member": True,
    },
    {
        "name": "Hungary",
        "alpha2": "HU", "alpha3": "HUN", "numeric": "348",
        "capital": "Budapest",
        "continent": "Europe", "region": "Europe", "subregion": "Eastern Europe",
        "currency": "HUF", "currency_name": "Hungarian forint",
        "calling_code": "+36", "tld": ".hu",
        "languages": ["Hungarian"], "un_member": True,
    },
    {
        "name": "Ukraine",
        "alpha2": "UA", "alpha3": "UKR", "numeric": "804",
        "capital": "Kyiv",
        "continent": "Europe", "region": "Europe", "subregion": "Eastern Europe",
        "currency": "UAH", "currency_name": "Ukrainian hryvnia",
        "calling_code": "+380", "tld": ".ua",
        "languages": ["Ukrainian"], "un_member": True,
    },
    {
        "name": "Romania",
        "alpha2": "RO", "alpha3": "ROU", "numeric": "642",
        "capital": "Bucharest",
        "continent": "Europe", "region": "Europe", "subregion": "Eastern Europe",
        "currency": "RON", "currency_name": "Romanian leu",
        "calling_code": "+40", "tld": ".ro",
        "languages": ["Romanian"], "un_member": True,
    },
    {
        "name": "Bulgaria",
        "alpha2": "BG", "alpha3": "BGR", "numeric": "100",
        "capital": "Sofia",
        "continent": "Europe", "region": "Europe", "subregion": "Eastern Europe",
        "currency": "BGN", "currency_name": "Bulgarian lev",
        "calling_code": "+359", "tld": ".bg",
        "languages": ["Bulgarian"], "un_member": True,
    },
    {
        "name": "Croatia",
        "alpha2": "HR", "alpha3": "HRV", "numeric": "191",
        "capital": "Zagreb",
        "continent": "Europe", "region": "Europe", "subregion": "Southern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+385", "tld": ".hr",
        "languages": ["Croatian"], "un_member": True,
    },
    {
        "name": "Luxembourg",
        "alpha2": "LU", "alpha3": "LUX", "numeric": "442",
        "capital": "Luxembourg City",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+352", "tld": ".lu",
        "languages": ["Luxembourgish", "French", "German"], "un_member": True,
    },
    {
        "name": "Monaco",
        "alpha2": "MC", "alpha3": "MCO", "numeric": "492",
        "capital": "Monaco",
        "continent": "Europe", "region": "Europe", "subregion": "Western Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+377", "tld": ".mc",
        "languages": ["French"], "un_member": True,
    },
    {
        "name": "Vatican City",
        "alpha2": "VA", "alpha3": "VAT", "numeric": "336",
        "capital": "Vatican City",
        "continent": "Europe", "region": "Europe", "subregion": "Southern Europe",
        "currency": "EUR", "currency_name": "Euro",
        "calling_code": "+379", "tld": ".va",
        "languages": ["Italian", "Latin"], "un_member": False,
    },
    # ---- Asia (rest) --------------------------------------------------
    {
        "name": "Singapore",
        "alpha2": "SG", "alpha3": "SGP", "numeric": "702",
        "capital": "Singapore",
        "continent": "Asia", "region": "Asia", "subregion": "South-eastern Asia",
        "currency": "SGD", "currency_name": "Singapore dollar",
        "calling_code": "+65", "tld": ".sg",
        "languages": ["English", "Mandarin", "Malay", "Tamil"], "un_member": True,
    },
    {
        "name": "Thailand",
        "alpha2": "TH", "alpha3": "THA", "numeric": "764",
        "capital": "Bangkok",
        "continent": "Asia", "region": "Asia", "subregion": "South-eastern Asia",
        "currency": "THB", "currency_name": "Thai baht",
        "calling_code": "+66", "tld": ".th",
        "languages": ["Thai"], "un_member": True,
    },
    {
        "name": "Vietnam",
        "alpha2": "VN", "alpha3": "VNM", "numeric": "704",
        "capital": "Hanoi",
        "continent": "Asia", "region": "Asia", "subregion": "South-eastern Asia",
        "currency": "VND", "currency_name": "Vietnamese đồng",
        "calling_code": "+84", "tld": ".vn",
        "languages": ["Vietnamese"], "un_member": True,
    },
    {
        "name": "Malaysia",
        "alpha2": "MY", "alpha3": "MYS", "numeric": "458",
        "capital": "Kuala Lumpur",
        "continent": "Asia", "region": "Asia", "subregion": "South-eastern Asia",
        "currency": "MYR", "currency_name": "Malaysian ringgit",
        "calling_code": "+60", "tld": ".my",
        "languages": ["Malay"], "un_member": True,
    },
    {
        "name": "Philippines",
        "alpha2": "PH", "alpha3": "PHL", "numeric": "608",
        "capital": "Manila",
        "continent": "Asia", "region": "Asia", "subregion": "South-eastern Asia",
        "currency": "PHP", "currency_name": "Philippine peso",
        "calling_code": "+63", "tld": ".ph",
        "languages": ["Filipino", "English"], "un_member": True,
    },
    {
        "name": "Pakistan",
        "alpha2": "PK", "alpha3": "PAK", "numeric": "586",
        "capital": "Islamabad",
        "continent": "Asia", "region": "Asia", "subregion": "Southern Asia",
        "currency": "PKR", "currency_name": "Pakistani rupee",
        "calling_code": "+92", "tld": ".pk",
        "languages": ["Urdu", "English"], "un_member": True,
    },
    {
        "name": "Bangladesh",
        "alpha2": "BD", "alpha3": "BGD", "numeric": "050",
        "capital": "Dhaka",
        "continent": "Asia", "region": "Asia", "subregion": "Southern Asia",
        "currency": "BDT", "currency_name": "Bangladeshi taka",
        "calling_code": "+880", "tld": ".bd",
        "languages": ["Bengali"], "un_member": True,
    },
    {
        "name": "Iran",
        "alpha2": "IR", "alpha3": "IRN", "numeric": "364",
        "capital": "Tehran",
        "continent": "Asia", "region": "Asia", "subregion": "Southern Asia",
        "currency": "IRR", "currency_name": "Iranian rial",
        "calling_code": "+98", "tld": ".ir",
        "languages": ["Persian"], "un_member": True,
    },
    {
        "name": "Israel",
        "alpha2": "IL", "alpha3": "ISR", "numeric": "376",
        "capital": "Jerusalem",
        "continent": "Asia", "region": "Asia", "subregion": "Western Asia",
        "currency": "ILS", "currency_name": "Israeli new shekel",
        "calling_code": "+972", "tld": ".il",
        "languages": ["Hebrew", "Arabic"], "un_member": True,
    },
    {
        "name": "United Arab Emirates",
        "alpha2": "AE", "alpha3": "ARE", "numeric": "784",
        "capital": "Abu Dhabi",
        "continent": "Asia", "region": "Asia", "subregion": "Western Asia",
        "currency": "AED", "currency_name": "United Arab Emirates dirham",
        "calling_code": "+971", "tld": ".ae",
        "languages": ["Arabic"], "un_member": True,
    },
    {
        "name": "Qatar",
        "alpha2": "QA", "alpha3": "QAT", "numeric": "634",
        "capital": "Doha",
        "continent": "Asia", "region": "Asia", "subregion": "Western Asia",
        "currency": "QAR", "currency_name": "Qatari riyal",
        "calling_code": "+974", "tld": ".qa",
        "languages": ["Arabic"], "un_member": True,
    },
    # ---- Oceania ------------------------------------------------------
    {
        "name": "New Zealand",
        "alpha2": "NZ", "alpha3": "NZL", "numeric": "554",
        "capital": "Wellington",
        "continent": "Oceania", "region": "Oceania", "subregion": "Australia and New Zealand",
        "currency": "NZD", "currency_name": "New Zealand dollar",
        "calling_code": "+64", "tld": ".nz",
        "languages": ["English", "Māori"], "un_member": True,
    },
    {
        "name": "Fiji",
        "alpha2": "FJ", "alpha3": "FJI", "numeric": "242",
        "capital": "Suva",
        "continent": "Oceania", "region": "Oceania", "subregion": "Melanesia",
        "currency": "FJD", "currency_name": "Fijian dollar",
        "calling_code": "+679", "tld": ".fj",
        "languages": ["English", "Fijian", "Hindi"], "un_member": True,
    },
    # ---- Africa -------------------------------------------------------
    {
        "name": "Nigeria",
        "alpha2": "NG", "alpha3": "NGA", "numeric": "566",
        "capital": "Abuja",
        "continent": "Africa", "region": "Africa", "subregion": "Western Africa",
        "currency": "NGN", "currency_name": "Nigerian naira",
        "calling_code": "+234", "tld": ".ng",
        "languages": ["English"], "un_member": True,
    },
    {
        "name": "Egypt",
        "alpha2": "EG", "alpha3": "EGY", "numeric": "818",
        "capital": "Cairo",
        "continent": "Africa", "region": "Africa", "subregion": "Northern Africa",
        "currency": "EGP", "currency_name": "Egyptian pound",
        "calling_code": "+20", "tld": ".eg",
        "languages": ["Arabic"], "un_member": True,
    },
    {
        "name": "Kenya",
        "alpha2": "KE", "alpha3": "KEN", "numeric": "404",
        "capital": "Nairobi",
        "continent": "Africa", "region": "Africa", "subregion": "Eastern Africa",
        "currency": "KES", "currency_name": "Kenyan shilling",
        "calling_code": "+254", "tld": ".ke",
        "languages": ["Swahili", "English"], "un_member": True,
    },
    {
        "name": "Ethiopia",
        "alpha2": "ET", "alpha3": "ETH", "numeric": "231",
        "capital": "Addis Ababa",
        "continent": "Africa", "region": "Africa", "subregion": "Eastern Africa",
        "currency": "ETB", "currency_name": "Ethiopian birr",
        "calling_code": "+251", "tld": ".et",
        "languages": ["Amharic"], "un_member": True,
    },
    {
        "name": "Morocco",
        "alpha2": "MA", "alpha3": "MAR", "numeric": "504",
        "capital": "Rabat",
        "continent": "Africa", "region": "Africa", "subregion": "Northern Africa",
        "currency": "MAD", "currency_name": "Moroccan dirham",
        "calling_code": "+212", "tld": ".ma",
        "languages": ["Arabic", "Berber"], "un_member": True,
    },
    {
        "name": "Ghana",
        "alpha2": "GH", "alpha3": "GHA", "numeric": "288",
        "capital": "Accra",
        "continent": "Africa", "region": "Africa", "subregion": "Western Africa",
        "currency": "GHS", "currency_name": "Ghanaian cedi",
        "calling_code": "+233", "tld": ".gh",
        "languages": ["English"], "un_member": True,
    },
    {
        "name": "Tanzania",
        "alpha2": "TZ", "alpha3": "TZA", "numeric": "834",
        "capital": "Dodoma",
        "continent": "Africa", "region": "Africa", "subregion": "Eastern Africa",
        "currency": "TZS", "currency_name": "Tanzanian shilling",
        "calling_code": "+255", "tld": ".tz",
        "languages": ["Swahili", "English"], "un_member": True,
    },
    # ---- Americas (rest) ----------------------------------------------
    {
        "name": "Chile",
        "alpha2": "CL", "alpha3": "CHL", "numeric": "152",
        "capital": "Santiago",
        "continent": "South America", "region": "Americas", "subregion": "South America",
        "currency": "CLP", "currency_name": "Chilean peso",
        "calling_code": "+56", "tld": ".cl",
        "languages": ["Spanish"], "un_member": True,
    },
    {
        "name": "Colombia",
        "alpha2": "CO", "alpha3": "COL", "numeric": "170",
        "capital": "Bogotá",
        "continent": "South America", "region": "Americas", "subregion": "South America",
        "currency": "COP", "currency_name": "Colombian peso",
        "calling_code": "+57", "tld": ".co",
        "languages": ["Spanish"], "un_member": True,
    },
    {
        "name": "Peru",
        "alpha2": "PE", "alpha3": "PER", "numeric": "604",
        "capital": "Lima",
        "continent": "South America", "region": "Americas", "subregion": "South America",
        "currency": "PEN", "currency_name": "Peruvian sol",
        "calling_code": "+51", "tld": ".pe",
        "languages": ["Spanish"], "un_member": True,
    },
    {
        "name": "Venezuela",
        "alpha2": "VE", "alpha3": "VEN", "numeric": "862",
        "capital": "Caracas",
        "continent": "South America", "region": "Americas", "subregion": "South America",
        "currency": "VES", "currency_name": "Venezuelan bolívar",
        "calling_code": "+58", "tld": ".ve",
        "languages": ["Spanish"], "un_member": True,
    },
    {
        "name": "Cuba",
        "alpha2": "CU", "alpha3": "CUB", "numeric": "192",
        "capital": "Havana",
        "continent": "North America", "region": "Americas", "subregion": "Caribbean",
        "currency": "CUP", "currency_name": "Cuban peso",
        "calling_code": "+53", "tld": ".cu",
        "languages": ["Spanish"], "un_member": True,
    },
    # ---- Taiwan (special case: not a UN member) -----------------------
    {
        "name": "Taiwan",
        "alpha2": "TW", "alpha3": "TWN", "numeric": "158",
        "capital": "Taipei",
        "continent": "Asia", "region": "Asia", "subregion": "Eastern Asia",
        "currency": "TWD", "currency_name": "New Taiwan dollar",
        "calling_code": "+886", "tld": ".tw",
        "languages": ["Mandarin"], "un_member": False,
    },
]
